# Generated by Django 4.1.1 on 2022-10-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_start_date_alter_payment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
