# Generated by Django 4.1.1 on 2023-01-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_gender_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='entrydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
